[workspace]

members = [
    "arduboy",
    "sdl",
    "libretro",
    "libretro_std",
    "libretro_psvita",
]

[profile.release]
debug = true
panic = 'abort'
# lto = true
lto = "fat"
codegen-units = 1

