[workspace]

members = [
    "arduboy",
    "sdl",
    "report",
    "libretro",
    "libretro_std",
    "libretro_psvita",
]

resolver = "2"

[profile.release]
# debug = true
# panic = 'abort'
# lto = true
# lto = "fat"
# codegen-units = 1

