name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: ["", "vec_unchecked", "std", "std,stats"]
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - run: ci/setup.sh
      - run: ci/test.sh build "${{ matrix.features }}"
  unit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: ["", "vec_unchecked", "std"]
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - run: ci/setup.sh
      - run: ci/test.sh unit "${{ matrix.features }}"
  vector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - run: ci/setup.sh
      - run: ci/test.sh vector
