[package]
name = "arduboy"
version = "0.1.0"
authors = ["Dhole <dhole@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = { version = "0.4", default-features = false }
log = { version = "0.4.8", default-features = false }
# env_logger = "0.7.0"
num-traits = { version = "0.2", default-features = false }
num-derive = "0.3"

[features]
default = ["std"]
std = []
